services:
  n8n:
    image: n8nio/n8n:1.123.15
    restart: always
    container_name: n8n-main
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=your_custom_auth_token_here
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # etc.

  task-runners:
    build:
      context: .
      dockerfile: Dockerfile.runners
    restart: always
    container_name: n8n-runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=your_custom_auth_token_here
      # etc.
    depends_on:
      - n8n
    volumes:
      - ./skyfield-data:/data/skyfield

volumes:
  n8n_data: