[project]
name = "sat-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytz>=2025.2",
    "requests>=2.32.5",
    "skyfield>=1.53",
]
